name: epg_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  xml: ^6.5.0
  freezed_annotation: ^3.0.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  auto_route: ^10.0.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  internet_connection_checker_plus: ^2.7.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  path_provider: ^2.1.5
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  auto_route_generator: ^10.0.1
  hive_ce_generator: ^1.8.2

flutter:
  uses-material-design: true
