// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:epg_test/core/services/local_db/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChannelAdapter());
    registerAdapter(ChannelCacheAdapter());
    registerAdapter(ProgrammeAdapter());
    registerAdapter(ProgrammeCacheAdapter());
  }
}
